version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:${APP_PORT}"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
