version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Linter
        command: yarn lint

    - run:
        name: Test
        command: yarn junit

    - store_test_results:
        path: test-results
