version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    - image: circleci/postgres:latest
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: circle_test

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: cp .env.example .env
    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Linter
        command: yarn lint

    - run:
        name: Test
        command: yarn junit
        environment:
          DB_HOST: localhost
          DB_USERNAME: circleci
          DB_DATABASE: circle_test

    - run:
        name: Coverage
        command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose

    - store_test_results:
        path: test-results
